// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportEvidence(arg1) {
  return window['go']['main']['App']['ExportEvidence'](arg1);
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetFlows() {
  return window['go']['main']['App']['GetFlows']();
}

export function GetPacketCount() {
  return window['go']['main']['App']['GetPacketCount']();
}

export function GetPackets(arg1, arg2) {
  return window['go']['main']['App']['GetPackets'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTopology() {
  return window['go']['main']['App']['GetTopology']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsCapturing() {
  return window['go']['main']['App']['IsCapturing']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function LoadPCAP(arg1) {
  return window['go']['main']['App']['LoadPCAP'](arg1);
}

export function StartCapture(arg1, arg2) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
