// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAlerts():Promise<Array<main.AlertDTO>>;

export function GetFiles():Promise<Array<main.FileDTO>>;

export function GetFlows():Promise<Array<main.FlowDTO>>;

export function GetPacketCount():Promise<number>;

export function GetPackets(arg1:number,arg2:number):Promise<Array<main.PacketDTO>>;

export function GetStats():Promise<main.StatsDTO>;

export function GetSystemInfo():Promise<{[key: string]: any}>;

export function GetVersion():Promise<string>;

export function IsCapturing():Promise<boolean>;

export function ListInterfaces():Promise<Array<main.InterfaceInfo>>;

export function LoadPCAP(arg1:string):Promise<void>;

export function StartCapture(arg1:string,arg2:string):Promise<void>;

export function StopCapture():Promise<void>;
