// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo():Promise<{[key: string]: any}>;

export function GetVersion():Promise<string>;
